[workspace]
members = [
    "crates/agsv-cli",
    "crates/agsv-control",
    "crates/agsv-core",
    "crates/agsv-protocol",
    "crates/agsv-runtime",
    "crates/agsv-session",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/kumaaa-inc/agent-supervisor"
rust-version = "1.85"
version = "0.2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
